services:
  nginx-server:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - "8080:80"  # Aucun conflit avec Traefik
    volumes:
      - ./nginx:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - vps-network
      
  reverse-proxy:
    image: traefik:v2.3
    container_name: reverse-proxy
    command:
      - "--api.insecure=false"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=peter.binate.project@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - vps-network

  myless-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myless
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    networks:
      - vps-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-app.rule=Host(`vps108078.serveur-vps.net`)"
      - "traefik.http.routers.web-app.entrypoints=websecure"
      - "traefik.http.routers.web-app.tls=true"
      - "traefik.http.routers.web-app.tls.certresolver=myresolver"
      - "traefik.http.services.wep-app.loadbalancer.server.port=3000"

networks:
  vps-network:
    external: true